// ESLint flat config (v9+)
const js = require('@eslint/js');
const globals = require('globals');

module.exports = [
  js.configs.recommended,
  {
    files: ['js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        // Globals shared across modules in this project (loaded via <script> tags)
        DB: 'writable',
        currentUser: 'writable',
        currentRole: 'writable',
        currentPage: 'writable',
        currentLang: 'writable',
        notifPanelOpen: 'writable',
        INSTITUTE: 'readonly',
        T: 'readonly',
        t: 'readonly',
        tt: 'readonly',
        applyLangToDOM: 'readonly',
        loadSavedLang: 'readonly',
        pages: 'writable',
        navConfig: 'readonly',
        PUSH: 'writable',
        SESSION_TIMEOUT: 'readonly',
        SESSION_WARNING: 'readonly',
        // Functions shared across modules
        saveDB: 'readonly',
        loadDB: 'readonly',
        autoSave: 'readonly',
        hashPassword: 'readonly',
        verifyPassword: 'readonly',
        upgradePasswordIfNeeded: 'readonly',
        migratePasswords: 'readonly',
        startSessionWatcher: 'readonly',
        stopSessionWatcher: 'readonly',
        resetSessionTimer: 'readonly',
        updateSessionIndicator: 'readonly',
        showToast: 'readonly',
        showModal: 'readonly',
        closeModal: 'readonly',
        closeModalDirect: 'readonly',
        navigateTo: 'readonly',
        buildNav: 'readonly',
        buildBottomNav: 'readonly',
        buildNotifPanel: 'readonly',
        getDefaultPage: 'readonly',
        toggleSidebar: 'readonly',
        closeSidebar: 'readonly',
        toggleNotifPanel: 'readonly',
        toggleFab: 'readonly',
        closeFab: 'readonly',
        loadSavedTheme: 'readonly',
        levelBadge: 'readonly',
        gradeBadge: 'readonly',
        pctBar: 'readonly',
        juzsWidget: 'readonly',
        JUZ_NAMES: 'readonly',
        doLogin: 'readonly',
        doLogout: 'readonly',
        doRegister: 'readonly',
        signInWithGoogle: 'readonly',
        showStep: 'readonly',
        showRegisterForm: 'readonly',
        showForgotPassword: 'readonly',
        hideForgotPassword: 'readonly',
        checkFpEmail: 'readonly',
        doResetPassword: 'readonly',
        setLang: 'readonly',
        setLoginLang: 'readonly',
        openWeakStudentsModal: 'readonly',
        openCircleModal: 'readonly',
        getParentStudent: 'readonly',
        renderParentNoStudent: 'readonly',
        initApp: 'readonly',
        // Modal & misc
        openModal: 'readonly',
        // Quran data
        QURAN_SURAHS: 'readonly',
        // Exam helpers (window.* but used cross-file)
        selectExamType: 'readonly',
        selectDifficulty: 'readonly',
        startExam: 'readonly',
        rateAnswer: 'readonly',
        // Teacher session helpers
        onSessionStudentChange: 'readonly',
        filterSurahs: 'readonly',
        openSurahDropdown: 'readonly',
        surahKeyNav: 'readonly',
        validateAyahRange: 'readonly',
        validateNewAyah: 'readonly',
        syncNewCount: 'readonly',
        saveSession: 'readonly',
        switchStudentFile: 'readonly',
        openStudentModal: 'readonly',
        exportStudentPDF: 'readonly',
        renderStudentReport: 'readonly',
        teacherToggleRec: 'readonly',
        teacherSendNotif: 'readonly',
        teacherMarkAll: 'readonly',
        saveTeacherAtt: 'readonly',
        setAtt: 'readonly',
        parentToggleRec: 'readonly',
        parentSendNotif: 'readonly',
        buildTodayTask: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-redeclare': 'off', // legacy var-style code
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-prototype-builtins': 'off',
      'no-inner-declarations': 'off',
      eqeqeq: ['warn', 'smart'],
    },
  },
  {
    files: ['server.js', 'eslint.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
    rules: {
      'no-unused-vars': 'warn',
    },
  },
  {
    ignores: [
      'node_modules/**',
      '.firebase/**',
      '.agents/**',
      '.git/**',
      'index.original.html',
    ],
  },
];
